// Code generated by mdatagen. DO NOT EDIT.

// Package metadata contains the autogenerated telemetry and
// build information for the receiver/nroracledb component.
package metadata

import (
	"go.opentelemetry.io/collector/component"
)

var (
	Type      = component.MustNewType("nroracledb")
	ScopeName = "github.com/newrelic-forks/opentelemetry-collector-contrib/receiver/nroracledbreceiver"
)

const (
	LogsStability    = component.StabilityLevelDevelopment
	MetricsStability = component.StabilityLevelAlpha
)
