// Code generated by mdatagen. DO NOT EDIT.

<<<<<<<< HEAD:processor/rollingspanlatencyprocessor/generated_package_test.go
package rollingspanlatencyprocessor
========
package filter
>>>>>>>> pre-release:internal/filter/generated_package_test.go

import (
	"testing"

	"go.uber.org/goleak"
)

func TestMain(m *testing.M) {
	goleak.VerifyTestMain(m)
}
