// Code generated by mdatagen. DO NOT EDIT.

package metadata

import (
	"go.opentelemetry.io/collector/featuregate"
)

var ReceiverNrsqlserverRemoveServerResourceAttributeFeatureGate = featuregate.GlobalRegistry().MustRegister(
	"receiver.nrsqlserver.RemoveServerResourceAttribute",
	featuregate.StageAlpha,
	featuregate.WithRegisterDescription("When enabled, the server.address and server.port resource attributes are removed from metrics."),
	featuregate.WithRegisterReferenceURL("https://github.com/open-telemetry/opentelemetry-collector-contrib/pull/40141"),
	featuregate.WithRegisterFromVersion("v0.129.0"),
)
