// Code generated by mdatagen. DO NOT EDIT.

// Package metadata contains the autogenerated telemetry and
// build information for the receiver/nrpostgresql component.
package metadata

import (
	"go.opentelemetry.io/collector/component"
)

var (
	Type      = component.MustNewType("nrpostgresql")
	ScopeName = "github.com/newrelic-forks/opentelemetry-collector-contrib/receiver/nrpostgresqlreceiver"
)

const (
	LogsStability    = component.StabilityLevelDevelopment
	MetricsStability = component.StabilityLevelBeta
)
